version: '3.9'

volumes:
  
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /opt/docker/wpa-free_web/dbdata
  
services:
  
  wpa-db:
    image: mariadb
    container_name: wpa-mariadb
    hostname: ${host}
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${root_password}
      - MYSQL_DATABASE=${database}
      - MYSQL_USER=${user}
      - MYSQL_PASSWORD=${password}
      - TZ=${TZ}
  
  wpa-app:
    build:
      context: ./
    container_name: wpa-app
    hostname: wpa-app
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=${TZ}
    extra_hosts:
      - "host.docker.internal:host-gateway"

  wpa-proxy:
    image: caddy:latest
    container_name: wpa-proxy
    hostname: wpa-proxy
    restart: always
    ports:
      - 443:443
      - 80:80
    volumes:
      - ./data/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

