version: '3.9'

services:
  webapp:
    build:
      context: ./
    container_name: webapp
    hostname: webapp
    restart: always
    ports:
      - 8000:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
