version: '3.9'

services:

  webapp:
    build: 
      context: ./
    container_name: webapp
    hostname: webapp
    network_mode: host
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./config/db.sqlite3:/free-server/db.sqlite3
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=America/Sao_Paulo
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
        window: 20s
      placement:
        constraints:
          - node.role==manager

